### ISSUE TITLE
Running Dictionary command says "Mac is required"

### ISSUE THREAD

**Issue by aankittcoolest** [itchyny/dictionary.vim#15]
1. Trying using this plugin on babun with cygwin (having gcc and vimproc installed)
2. Following error is shown.
"Mac is required".
![image](https://user-images.githubusercontent.com/7322912/39111161-158c2bde-470f-11e8-961f-e764c0b8fa4d.png)

**Comment by itchyny** [comment]
This plugin requires Dictionary.app which is a standard application on macOS.

**Comment by aankittcoolest** [comment]
I see. Thanks.
Closing it 😀
I cannot use it then.
